# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_parking
    username: smart_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: smart-parking-system

server:
  port: 8081
